const costTable: Record<string, number> = {
  // ── GCP ──────────────────────────────────────────────────────────────────
  "gcp:compute/instance:Instance": 25,
  "gcp:compute/network:Network": 0,
  "gcp:compute/subnetwork:Subnetwork": 0,
  "gcp:compute/firewall:Firewall": 0,
  "gcp:compute/globalAddress:GlobalAddress": 2,
  "gcp:compute/address:Address": 2,
  "gcp:compute/router:Router": 0,
  "gcp:compute/routerNat:RouterNat": 5,
  "gcp:compute/backendService:BackendService": 0,
  "gcp:compute/urlMap:UrlMap": 0,
  "gcp:compute/targetHttpsProxy:TargetHttpsProxy": 0,
  "gcp:compute/globalForwardingRule:GlobalForwardingRule": 20,
  "gcp:storage/bucket:Bucket": 3,
  "gcp:sql/databaseInstance:DatabaseInstance": 30,
  "gcp:sql/database:Database": 0,
  "gcp:sql/user:User": 0,
  "gcp:redis/instance:Instance": 25,
  "gcp:memcache/instance:Instance": 20,
  "gcp:cloudfunctions/function:Function": 2,
  "gcp:cloudfunctionsv2/function:Function": 2,
  "gcp:cloudrun/service:Service": 5,
  "gcp:container/cluster:Cluster": 75,
  "gcp:container/nodePool:NodePool": 50,
  "gcp:bigquery/dataset:Dataset": 0,
  "gcp:bigquery/table:Table": 5,
  "gcp:pubsub/topic:Topic": 1,
  "gcp:pubsub/subscription:Subscription": 1,
  "gcp:dns/managedZone:ManagedZone": 1,
  "gcp:dns/recordSet:RecordSet": 0,
  "gcp:iam/serviceAccount:ServiceAccount": 0,
  "gcp:projects/iAMMember:IAMMember": 0,
  "gcp:secretmanager/secret:Secret": 1,
  "gcp:secretmanager/secretVersion:SecretVersion": 0,
  "gcp:artifactregistry/repository:Repository": 2,
  "gcp:monitoring/alertPolicy:AlertPolicy": 0,

  // ── AWS ──────────────────────────────────────────────────────────────────
  "aws:ec2/instance:Instance": 30,
  "aws:ec2/vpc:Vpc": 0,
  "aws:ec2/subnet:Subnet": 0,
  "aws:ec2/securityGroup:SecurityGroup": 0,
  "aws:ec2/internetGateway:InternetGateway": 0,
  "aws:ec2/routeTable:RouteTable": 0,
  "aws:ec2/routeTableAssociation:RouteTableAssociation": 0,
  "aws:ec2/eip:Eip": 4,
  "aws:ec2/natGateway:NatGateway": 45,
  "aws:s3/bucket:Bucket": 3,
  "aws:s3/bucketV2:BucketV2": 3,
  "aws:rds/instance:Instance": 25,
  "aws:rds/cluster:Cluster": 50,
  "aws:rds/subnetGroup:SubnetGroup": 0,
  "aws:elasticache/cluster:Cluster": 20,
  "aws:elasticache/replicationGroup:ReplicationGroup": 40,
  "aws:elasticache/subnetGroup:SubnetGroup": 0,
  "aws:lambda/function:Function": 2,
  "aws:apigateway/restApi:RestApi": 5,
  "aws:apigatewayv2/api:Api": 5,
  "aws:ecs/cluster:Cluster": 0,
  "aws:ecs/service:Service": 30,
  "aws:ecs/taskDefinition:TaskDefinition": 0,
  "aws:ecr/repository:Repository": 2,
  "aws:cloudfront/distribution:Distribution": 10,
  "aws:route53/zone:Zone": 1,
  "aws:route53/record:Record": 0,
  "aws:iam/role:Role": 0,
  "aws:iam/policy:Policy": 0,
  "aws:iam/rolePolicyAttachment:RolePolicyAttachment": 0,
  "aws:lb/loadBalancer:LoadBalancer": 20,
  "aws:lb/targetGroup:TargetGroup": 0,
  "aws:lb/listener:Listener": 0,
  "aws:alb/loadBalancer:LoadBalancer": 20,
  "aws:alb/targetGroup:TargetGroup": 0,
  "aws:alb/listener:Listener": 0,
  "aws:sns/topic:Topic": 1,
  "aws:sqs/queue:Queue": 1,
  "aws:dynamodb/table:Table": 5,
  "aws:ses/emailIdentity:EmailIdentity": 0,
  "aws:cognito/userPool:UserPool": 5,
};

export function estimateMonthlyCost(type: string): number | null {
  return costTable[type] ?? null;
}

export function totalEstimatedCost(types: string[]): number {
  return types.reduce((sum, type) => sum + (costTable[type] ?? 5), 0);
}
